# Generated by Django 5.2.4 on 2025-07-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Danh mục')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Thương hiệu')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
    ]
