# Generated by Django 5.2.4 on 2025-07-30 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_product_in_stock_product_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
